//
//  Keyboard.swift
//  seikoUcKeyboard
//
//  Created by Giulio Furlan on 04/02/24.
//

import Foundation

class Keyboard {
    static let keys = [
        UcKey(value: 0x31, text: "1"),
        UcKey(value: 0x32, text: "2"),
        UcKey(value: 0x33, text: "3"),
        UcKey(value: 0x34, text: "4"),
        UcKey(value: 0x35, text: "5"),
        UcKey(value: 0x36, text: "6"),
        UcKey(value: 0x37, text: "7"),
        UcKey(value: 0x38, text: "8"),
        UcKey(value: 0x39, text: "9"),
        UcKey(value: 0x30, text: "0"),
        
        UcKey(value: 0x71, text: "q"),
        UcKey(value: 0x77, text: "w"),
        UcKey(value: 0x65, text: "e"),
        UcKey(value: 0x72, text: "r"),
        UcKey(value: 0x74, text: "t"),
        UcKey(value: 0x79, text: "y"),
        UcKey(value: 0x75, text: "u"),
        UcKey(value: 0x69, text: "i"),
        UcKey(value: 0x6F, text: "o"),
        UcKey(value: 0x70, text: "p"),
        
        UcKey(value: 0x61, text: "a"),
        UcKey(value: 0x73, text: "s"),
        UcKey(value: 0x64, text: "d"),
        UcKey(value: 0x66, text: "f"),
        UcKey(value: 0x67, text: "g"),
        UcKey(value: 0x68, text: "h"),
        UcKey(value: 0x6A, text: "j"),
        UcKey(value: 0x6B, text: "k"),
        UcKey(value: 0x6C, text: "l"),
        UcKey(value: 0x3F, text: "?"),
        
        UcKey(value: 0x7A, text: "z"),
        UcKey(value: 0x78, text: "x"),
        UcKey(value: 0x63, text: "c"),
        UcKey(value: 0x76, text: "v"),
        UcKey(value: 0x62, text: "b"),
        UcKey(value: 0x6E, text: "n"),
        UcKey(value: 0x6D, text: "m"),
        UcKey(value: 0x2F, text: "/"),
        UcKey(value: 0x2A, text: "*"),
        UcKey(value: 0x3E, text: ">"),
        
        UcKey(value: 0x2B, text: "+"),
        UcKey(value: 0x2D, text: "-"),
        UcKey(value: 0x7B, text: "×"),
        UcKey(value: 0x7D, text: "÷"),
        UcKey(value: 0x3D, text: "="),
        UcKey(value: 0x2E, text: "."),
        UcKey(value: 0x5B, text: "["),
        UcKey(value: 0x5D, text: "]"),
        UcKey(value: 0x2C, text: ","),
        UcKey(value: 0x3A, text: ":"),
        
        UcKey(value: 0x06, text: "M-A"),
        UcKey(value: 0x07, text: "M-B"),
        UcKey(value: 0x10, text: "CAL"),
        UcKey(value: 0x1F, text: "CNT▲"),
        UcKey(value: 0x0A, text: "▲"),
        UcKey(value: 0x09, text: "▶"),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        
        UcKey(value: nil, text: "SFT"),
        UcKey(value: nil, text: ""),
        UcKey(value: 0x20, text: "SPACE"),
        UcKey(value: nil, text: ""),
        UcKey(value: 0x08, text: "◀"),
        UcKey(value: 0x0B, text: "▼"),
        UcKey(value: 0x0D, text: "RETURN"),
        UcKey(value: 0x15, text: "RST"),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
    ]
    
    
    static let shiftKeys = [
        UcKey(value: 0x21, text: "!"),
        UcKey(value: 0x2F, text: "/"),
        UcKey(value: 0x23, text: "#"),
        UcKey(value: 0x24, text: "$"),
        UcKey(value: 0x25, text: "%"),
        UcKey(value: 0x26, text: "&"),
        UcKey(value: 0x27, text: "'"),
        UcKey(value: 0x28, text: "("),
        UcKey(value: 0x29, text: ")"),
        UcKey(value: 0x5E, text: "^"),
        
        UcKey(value: 0x51, text: "Q"),
        UcKey(value: 0x57, text: "W"),
        UcKey(value: 0x45, text: "E"),
        UcKey(value: 0x52, text: "R"),
        UcKey(value: 0x54, text: "T"),
        UcKey(value: 0x59, text: "Y"),
        UcKey(value: 0x55, text: "U"),
        UcKey(value: 0x49, text: "I"),
        UcKey(value: 0x4F, text: "O"),
        UcKey(value: 0x50, text: "P"),
        
        UcKey(value: 0x41, text: "A"),
        UcKey(value: 0x53, text: "S"),
        UcKey(value: 0x44, text: "D"),
        UcKey(value: 0x46, text: "F"),
        UcKey(value: 0x47, text: "G"),
        UcKey(value: 0x48, text: "H"),
        UcKey(value: 0x4A, text: "J"),
        UcKey(value: 0x4B, text: "K"),
        UcKey(value: 0x4C, text: "L"),
        UcKey(value: 0x5F, text: "_"),
        
        UcKey(value: 0x5A, text: "Z"),
        UcKey(value: 0x58, text: "X"),
        UcKey(value: 0x43, text: "C"),
        UcKey(value: 0x56, text: "V"),
        UcKey(value: 0x42, text: "B"),
        UcKey(value: 0x4E, text: "N"),
        UcKey(value: 0x4D, text: "M"),
        UcKey(value: 0x96, text: "🔔"),
        UcKey(value: 0x40, text: "@"),
        UcKey(value: 0x3C, text: "<"),
        
        UcKey(value: 0x9B, text: "✆"),
        UcKey(value: 0x9C, text: "✈"),
        UcKey(value: 0x9D, text: ""),
        UcKey(value: 0x9E, text: "🍷"),
        UcKey(value: 0x9F, text: "🤝"),
        UcKey(value: 0x97, text: "♠"),
        UcKey(value: 0x98, text: "♥"),
        UcKey(value: 0x99, text: "♦"),
        UcKey(value: 0x9A, text: "♣"),
        UcKey(value: 0x3B, text: ";"),
        
        UcKey(value: 0x06, text: "M-A"),
        UcKey(value: 0x07, text: "M-B"),
        UcKey(value: 0x10, text: "CAL"),
        UcKey(value: 0x12, text: "CNT▼"),
        UcKey(value: 0x0A, text: "▲"),
        UcKey(value: 0x09, text: "▶"),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
        
        UcKey(value: nil, text: "SFT"),
        UcKey(value: nil, text: ""),
        UcKey(value: 0x20, text: "SPACE"),
        UcKey(value: nil, text: ""),
        UcKey(value: 0x08, text: "◀"),
        UcKey(value: 0x0B, text: "▼"),
        UcKey(value: 0x0D, text: "RETURN"),
        UcKey(value: 0x15, text: "RST"),
        UcKey(value: nil, text: ""),
        UcKey(value: nil, text: ""),
    ]
}
